// Copyright (c) the go-ruby-sodium/sodium authors
//
// SPDX-License-Identifier: BSD-3-Clause

package sodium

import (
	"bytes"
	"encoding/hex"
	"errors"
	"testing"
)

// mustHex decodes a hex literal from a published test vector, failing the test
// on a malformed literal.
func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}

func repeat(b byte, n int) []byte {
	out := make([]byte, n)
	for i := range out {
		out[i] = b
	}
	return out
}

// --- RandomBytes -----------------------------------------------------------

func TestRandomBytes(t *testing.T) {
	a := RandomBytes(32)
	if len(a) != 32 {
		t.Fatalf("len = %d, want 32", len(a))
	}
	if bytes.Equal(a, make([]byte, 32)) {
		t.Fatal("RandomBytes returned all zeroes")
	}
}

func TestRandomBytesPanicsOnReaderFailure(t *testing.T) {
	defer func(orig func([]byte) (int, error)) { randRead = orig }(randRead)
	randRead = func([]byte) (int, error) { return 0, errors.New("boom") }
	defer func() {
		if r := recover(); r == nil {
			t.Fatal("expected panic when the CSPRNG fails")
		}
	}()
	RandomBytes(16)
}

// --- SecretBox (XSalsa20-Poly1305) -----------------------------------------
//
// Vector: expected ciphertext generated by the C implementation of NaCl
// (golang.org/x/crypto/nacl/secretbox reference test): key = 32×0x01,
// nonce = 24×0x02, message = 64×0x03.

func TestSecretBoxVector(t *testing.T) {
	key := repeat(0x01, 32)
	nonce := repeat(0x02, 24)
	msg := repeat(0x03, 64)
	want := mustHex(t, "8442bc313f4626f1359e3b50122b6ce6fe66ddfe7d39d14e637eb4fd5b45beadab55198df6ab5368439792a23c87db70acb6156dc5ef957ac04f6276cf6093b84be77ff0849cc33e34b7254d5a8f65ad")

	sb, err := NewSecretBox(key)
	if err != nil {
		t.Fatal(err)
	}
	ct, err := sb.Encrypt(nonce, msg)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(ct, want) {
		t.Fatalf("ciphertext\n got %x\nwant %x", ct, want)
	}
	pt, err := sb.Decrypt(nonce, ct)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(pt, msg) {
		t.Fatalf("roundtrip: got %x, want %x", pt, msg)
	}
}

func TestSecretBoxErrors(t *testing.T) {
	if _, err := NewSecretBox(repeat(0, 31)); !errors.Is(err, ErrLength) {
		t.Fatalf("short key: got %v", err)
	}
	sb, _ := NewSecretBox(repeat(1, 32))
	if _, err := sb.Encrypt(repeat(2, 23), nil); !errors.Is(err, ErrLength) {
		t.Fatalf("short nonce (encrypt): got %v", err)
	}
	if _, err := sb.Decrypt(repeat(2, 23), nil); !errors.Is(err, ErrLength) {
		t.Fatalf("short nonce (decrypt): got %v", err)
	}
	ct, _ := sb.Encrypt(repeat(2, 24), []byte("hello"))
	ct[0] ^= 0xff
	if _, err := sb.Decrypt(repeat(2, 24), ct); !errors.Is(err, ErrBadAuthenticator) {
		t.Fatalf("tampered ciphertext: got %v", err)
	}
}

// --- Box (Curve25519-XSalsa20-Poly1305) ------------------------------------
//
// Vector: golang.org/x/crypto/nacl/box reference test, expected generated by
// the C implementation of NaCl. privateKey1 = 32×0x01, publicKey1 derived from
// it, privateKey2 = 32×0x02, nonce = 24×0x04, message = 64×0x03.

func TestBoxVector(t *testing.T) {
	priv1, err := NewPrivateKey(repeat(0x01, 32))
	if err != nil {
		t.Fatal(err)
	}
	priv2, _ := NewPrivateKey(repeat(0x02, 32))
	pub1 := priv1.PublicKey()
	nonce := repeat(0x04, 24)
	msg := repeat(0x03, 64)
	want := mustHex(t, "78ea30b19d2341ebbdba54180f821eec265cf86312549bea8a37652a8bb94f07b78a73ed1708085e6ddd0e943bbdeb8755079a37eb31d86163ce241164a47629c0539f330b4914cd135b3855bc2a2dfc")

	sender := NewBox(pub1, priv2)
	ct, err := sender.Encrypt(nonce, msg)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(ct, want) {
		t.Fatalf("box ciphertext\n got %x\nwant %x", ct, want)
	}
	// The recipient (owner of priv1) reconstructs the same shared key and opens.
	pub2 := priv2.PublicKey()
	recipient := NewBox(pub2, priv1)
	pt, err := recipient.Decrypt(nonce, ct)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(pt, msg) {
		t.Fatalf("box roundtrip: got %x, want %x", pt, msg)
	}
	if !bytes.Equal(sender.SharedKey(), recipient.SharedKey()) {
		t.Fatal("shared keys differ between sender and recipient")
	}
}

func TestBoxKeyAccessors(t *testing.T) {
	priv := GeneratePrivateKey()
	if len(priv.Bytes()) != PrivateKeyBytes {
		t.Fatal("private key length")
	}
	pub := priv.PublicKey()
	rebuilt, err := NewPublicKey(pub.Bytes())
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(rebuilt.Bytes(), pub.Bytes()) {
		t.Fatal("public key round-trip mismatch")
	}
}

func TestBoxErrors(t *testing.T) {
	if _, err := NewPrivateKey(repeat(0, 31)); !errors.Is(err, ErrLength) {
		t.Fatalf("short private key: got %v", err)
	}
	if _, err := NewPublicKey(repeat(0, 31)); !errors.Is(err, ErrLength) {
		t.Fatalf("short public key: got %v", err)
	}
	b := NewBox(GeneratePrivateKey().PublicKey(), GeneratePrivateKey())
	if _, err := b.Encrypt(repeat(0, 23), nil); !errors.Is(err, ErrLength) {
		t.Fatalf("short nonce (encrypt): got %v", err)
	}
	if _, err := b.Decrypt(repeat(0, 23), nil); !errors.Is(err, ErrLength) {
		t.Fatalf("short nonce (decrypt): got %v", err)
	}
	ct, _ := b.Encrypt(repeat(0, 24), []byte("hi"))
	ct[len(ct)-1] ^= 0xff
	if _, err := b.Decrypt(repeat(0, 24), ct); !errors.Is(err, ErrBadAuthenticator) {
		t.Fatalf("tampered box: got %v", err)
	}
}

// --- SigningKey / VerifyKey (Ed25519) --------------------------------------
//
// Vectors: RFC 8032 test 1 (empty message) and test 2 (single-byte 0x72), the
// canonical Ed25519 vectors shipped in crypto/ed25519/testdata.

func TestEd25519Vectors(t *testing.T) {
	cases := []struct {
		seed, pub, msg, sig string
	}{
		{
			seed: "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60",
			pub:  "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
			msg:  "",
			sig:  "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b",
		},
		{
			seed: "4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb",
			pub:  "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c",
			msg:  "72",
			sig:  "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00",
		},
	}
	for i, c := range cases {
		sk, err := NewSigningKey(mustHex(t, c.seed))
		if err != nil {
			t.Fatalf("case %d: %v", i, err)
		}
		vk := sk.VerifyKey()
		if !bytes.Equal(vk.Bytes(), mustHex(t, c.pub)) {
			t.Fatalf("case %d: pubkey\n got %x\nwant %s", i, vk.Bytes(), c.pub)
		}
		msg := mustHex(t, c.msg)
		sig := sk.Sign(msg)
		if !bytes.Equal(sig, mustHex(t, c.sig)) {
			t.Fatalf("case %d: signature\n got %x\nwant %s", i, sig, c.sig)
		}
		if err := vk.Verify(sig, msg); err != nil {
			t.Fatalf("case %d: verify: %v", i, err)
		}
		if !bytes.Equal(sk.Seed(), mustHex(t, c.seed)) {
			t.Fatalf("case %d: seed round-trip", i)
		}
	}
}

func TestSigningKeyGenerate(t *testing.T) {
	sk := GenerateSigningKey()
	vk := sk.VerifyKey()
	rebuilt, err := NewVerifyKey(vk.Bytes())
	if err != nil {
		t.Fatal(err)
	}
	msg := []byte("attack at dawn")
	if err := rebuilt.Verify(sk.Sign(msg), msg); err != nil {
		t.Fatalf("verify with rebuilt key: %v", err)
	}
}

func TestSignErrors(t *testing.T) {
	if _, err := NewSigningKey(repeat(0, 31)); !errors.Is(err, ErrLength) {
		t.Fatalf("short seed: got %v", err)
	}
	if _, err := NewVerifyKey(repeat(0, 31)); !errors.Is(err, ErrLength) {
		t.Fatalf("short verify key: got %v", err)
	}
	sk := GenerateSigningKey()
	vk := sk.VerifyKey()
	msg := []byte("m")
	sig := sk.Sign(msg)
	if err := vk.Verify(repeat(0, 63), msg); !errors.Is(err, ErrLength) {
		t.Fatalf("short signature: got %v", err)
	}
	sig[0] ^= 0xff
	if err := vk.Verify(sig, msg); !errors.Is(err, ErrBadAuthenticator) {
		t.Fatalf("bad signature: got %v", err)
	}
}

// --- Hash (SHA-256 / SHA-512 / BLAKE2b) ------------------------------------

func TestHashVectors(t *testing.T) {
	if got := SHA256([]byte("abc")); !bytes.Equal(got, mustHex(t, "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")) {
		t.Fatalf("sha256: %x", got)
	}
	if got := SHA512([]byte("abc")); !bytes.Equal(got, mustHex(t, "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f")) {
		t.Fatalf("sha512: %x", got)
	}
	// RFC 7693 BLAKE2b-512("abc").
	b512, err := Blake2b([]byte("abc"), Blake2bOptions{DigestSize: 64})
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(b512, mustHex(t, "ba80a53f981c4d0d6a2797b69f12f6e94c212f14685ac4b74b12bb6fdbffa2d17d87c5392aab792dc252d5de4533cc9518d38aa8dbf1925ab92386edd4009923")) {
		t.Fatalf("blake2b-512: %x", b512)
	}
	// Default options give a 32-byte digest (crypto_generichash_BYTES).
	def, err := Blake2b([]byte("abc"), Blake2bOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if len(def) != Blake2bBytes {
		t.Fatalf("default digest size = %d", len(def))
	}
	// Keyed BLAKE2b is a MAC; the key changes the output.
	keyed, err := Blake2b([]byte("abc"), Blake2bOptions{DigestSize: 32, Key: repeat(0x42, 32)})
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Equal(keyed, def) {
		t.Fatal("keyed digest equals unkeyed digest")
	}
}

func TestBlake2bErrors(t *testing.T) {
	if _, err := Blake2b(nil, Blake2bOptions{DigestSize: 65}); !errors.Is(err, ErrLength) {
		t.Fatalf("oversize digest: got %v", err)
	}
	if _, err := Blake2b(nil, Blake2bOptions{DigestSize: -1}); !errors.Is(err, ErrLength) {
		t.Fatalf("undersize digest: got %v", err)
	}
	if _, err := Blake2b(nil, Blake2bOptions{Key: repeat(0, 65)}); !errors.Is(err, ErrLength) {
		t.Fatalf("oversize key: got %v", err)
	}
	if _, err := Blake2b(nil, Blake2bOptions{Salt: repeat(0, 16)}); !errors.Is(err, ErrCrypto) {
		t.Fatalf("salt: got %v", err)
	}
	if _, err := Blake2b(nil, Blake2bOptions{Personal: repeat(0, 16)}); !errors.Is(err, ErrCrypto) {
		t.Fatalf("personal: got %v", err)
	}
}

// --- Auth (HMAC) -----------------------------------------------------------
//
// Vectors: RFC 4231 test case 1. Key = 20×0x0b, data = "Hi There".

func TestHMACVectors(t *testing.T) {
	key := repeat(0x0b, 20)
	data := []byte("Hi There")

	sha256Want := mustHex(t, "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7")
	sha512Want := mustHex(t, "87aa7cdea5ef619d4ff0b4241a1d6cb02379f4e2ce4ec2787ad0b30545e17cdedaa833b7d6b8a702038b274eaea3f4e4be9d914eeb61f1702e696c203a126854")

	if got := NewHMACSHA256(key).Auth(data); !bytes.Equal(got, sha256Want) {
		t.Fatalf("hmac-sha256: %x", got)
	}
	if got := NewHMACSHA512(key).Auth(data); !bytes.Equal(got, sha512Want) {
		t.Fatalf("hmac-sha512: %x", got)
	}
	// HMAC-SHA-512-256 is HMAC-SHA-512 truncated to 32 bytes (libsodium crypto_auth).
	if got := NewHMACSHA512256(key).Auth(data); !bytes.Equal(got, sha512Want[:32]) {
		t.Fatalf("hmac-sha512256: %x", got)
	}
}

func TestHMACVerify(t *testing.T) {
	a := NewHMACSHA256(repeat(7, 32))
	msg := []byte("authentic")
	tag := a.Auth(msg)
	if err := a.Verify(tag, msg); err != nil {
		t.Fatalf("valid tag rejected: %v", err)
	}
	tag[0] ^= 0xff
	if err := a.Verify(tag, msg); !errors.Is(err, ErrBadAuthenticator) {
		t.Fatalf("forged tag accepted: %v", err)
	}
}

// --- PasswordHash (Argon2 / scrypt) ----------------------------------------

func TestArgon2Golden(t *testing.T) {
	pw := []byte("password")
	salt := []byte("somesalt-16bytes")
	// Goldens produced by golang.org/x/crypto/argon2 (itself validated against
	// the Argon2 reference KATs); these pin the wrapper's byte output.
	if got := Argon2id(pw, salt, 3, 4096, 1, 32); !bytes.Equal(got, mustHex(t, "bf5e448bf204e63d82fd6da18f7885ec517b2ddc1183645f01249aaeefb5f338")) {
		t.Fatalf("argon2id: %x", got)
	}
	if got := Argon2i(pw, salt, 3, 4096, 1, 32); !bytes.Equal(got, mustHex(t, "fac8fb5d23df2065ea72a360030b645deda20a83e3e121dc3d5232b1d4a9571b")) {
		t.Fatalf("argon2i: %x", got)
	}
	if got := Argon2id(pw, salt, 1, 8, 1, 16); !bytes.Equal(got, mustHex(t, "d1487ff35084d6d51e614262f8ea821e")) {
		t.Fatalf("argon2id small: %x", got)
	}
}

func TestScryptVectors(t *testing.T) {
	// RFC 7914 section 12 test vectors.
	got, err := Scrypt([]byte(""), []byte(""), 16, 1, 1, 64)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, mustHex(t, "77d6576238657b203b19ca42c18a0497f16b4844e3074ae8dfdffa3fede21442fcd0069ded0948f8326a753a0fc81f17e8d3e0fb2e0d3628cf35e20c38d18906")) {
		t.Fatalf("scrypt vector 1: %x", got)
	}
	got2, err := Scrypt([]byte("password"), []byte("NaCl"), 1024, 8, 16, 64)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got2, mustHex(t, "fdbabe1c9d3472007856e7190d01e9fe7c6ad7cbc8237830e77376634b3731622eaf30d92e22a3886ff109279d9830dac727afb94a83ee6d8360cbdfa2cc0640")) {
		t.Fatalf("scrypt vector 2: %x", got2)
	}
}

func TestScryptError(t *testing.T) {
	// n must be a power of two greater than 1.
	if _, err := Scrypt([]byte("x"), []byte("y"), 3, 8, 1, 32); !errors.Is(err, ErrCrypto) {
		t.Fatalf("invalid scrypt params: got %v", err)
	}
}

// --- GroupElement (Curve25519 scalar mult / X25519) ------------------------

func TestGroupElementVector(t *testing.T) {
	// RFC 7748 section 5.2, first X25519 test vector.
	scalar := mustHex(t, "a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4")
	u := mustHex(t, "e6db6867583030db3594c1a424b15f7c726624ec26b3353b10a903a6d0ab1c4c")
	want := mustHex(t, "c3da55379de9c6908e94ea4df28d084f32eccf03491c71f754b4075577a28552")

	ge, err := NewGroupElement(u)
	if err != nil {
		t.Fatal(err)
	}
	res, err := ge.Mult(scalar)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(res.Bytes(), want) {
		t.Fatalf("x25519\n got %x\nwant %x", res.Bytes(), want)
	}
}

func TestScalarMultBaseVector(t *testing.T) {
	// RFC 7748 section 6.1: Alice's public key from her private key.
	priv := mustHex(t, "77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a")
	want := mustHex(t, "8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a")
	got, err := ScalarMultBase(priv)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("scalarmult_base\n got %x\nwant %x", got, want)
	}
}

func TestGroupElementErrors(t *testing.T) {
	if _, err := NewGroupElement(repeat(0, 31)); !errors.Is(err, ErrLength) {
		t.Fatalf("short point: got %v", err)
	}
	ge, _ := NewGroupElement(repeat(0, 32))
	if _, err := ge.Mult(repeat(0, 31)); !errors.Is(err, ErrLength) {
		t.Fatalf("short scalar: got %v", err)
	}
	// An all-zero (small-order) point drives X25519 to an all-zero output,
	// which libsodium/x25519 rejects.
	if _, err := ge.Mult(repeat(1, 32)); !errors.Is(err, ErrBadAuthenticator) {
		t.Fatalf("small-order point: got %v", err)
	}
	if _, err := ScalarMultBase(repeat(0, 31)); !errors.Is(err, ErrLength) {
		t.Fatalf("short base scalar: got %v", err)
	}
}

// --- AEAD (ChaCha20-Poly1305 IETF / XChaCha20-Poly1305) --------------------

func TestChaCha20Poly1305IETFVector(t *testing.T) {
	// RFC 8439 section 2.8.2.
	key := mustHex(t, "808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f")
	nonce := mustHex(t, "070000004041424344454647")
	aad := mustHex(t, "50515253c0c1c2c3c4c5c6c7")
	pt := []byte("Ladies and Gentlemen of the class of '99: If I could offer you only one tip for the future, sunscreen would be it.")
	wantCT := mustHex(t, "d31a8d34648e60db7b86afbc53ef7ec2a4aded51296e08fea9e2b5a736ee62d63dbea45e8ca9671282fafb69da92728b1a71de0a9e060b2905d6a5b67ecd3b3692ddbd7f2d778b8c9803aee328091b58fab324e4fad675945585808b4831d7bc3ff4def08e4b7a9de576d26586cec64b6116")
	wantTag := mustHex(t, "1ae10b594f09e26a7e902ecbd0600691")

	a, err := NewChaCha20Poly1305IETF(key)
	if err != nil {
		t.Fatal(err)
	}
	if a.NonceBytes() != ChaCha20Poly1305IETFNonceBytes {
		t.Fatalf("nonce size = %d", a.NonceBytes())
	}
	ct, err := a.Encrypt(nonce, pt, aad)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(ct, append(append([]byte{}, wantCT...), wantTag...)) {
		t.Fatalf("aead ciphertext\n got %x", ct)
	}
	dec, err := a.Decrypt(nonce, ct, aad)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(dec, pt) {
		t.Fatalf("aead roundtrip mismatch")
	}
}

func TestXChaCha20Poly1305Roundtrip(t *testing.T) {
	key := RandomBytes(AEADKeyBytes)
	a, err := NewXChaCha20Poly1305IETF(key)
	if err != nil {
		t.Fatal(err)
	}
	if a.NonceBytes() != XChaCha20Poly1305IETFNonceBytes {
		t.Fatalf("nonce size = %d", a.NonceBytes())
	}
	nonce := RandomBytes(a.NonceBytes())
	pt := []byte("secret payload")
	aad := []byte("header")
	ct, err := a.Encrypt(nonce, pt, aad)
	if err != nil {
		t.Fatal(err)
	}
	dec, err := a.Decrypt(nonce, ct, aad)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(dec, pt) {
		t.Fatal("xchacha roundtrip mismatch")
	}
}

func TestAEADErrors(t *testing.T) {
	if _, err := NewChaCha20Poly1305IETF(repeat(0, 31)); !errors.Is(err, ErrLength) {
		t.Fatalf("short ietf key: got %v", err)
	}
	if _, err := NewXChaCha20Poly1305IETF(repeat(0, 31)); !errors.Is(err, ErrLength) {
		t.Fatalf("short xchacha key: got %v", err)
	}
	a, _ := NewChaCha20Poly1305IETF(repeat(1, 32))
	if _, err := a.Encrypt(repeat(0, 11), nil, nil); !errors.Is(err, ErrLength) {
		t.Fatalf("short nonce (encrypt): got %v", err)
	}
	if _, err := a.Decrypt(repeat(0, 11), nil, nil); !errors.Is(err, ErrLength) {
		t.Fatalf("short nonce (decrypt): got %v", err)
	}
	ct, _ := a.Encrypt(repeat(0, 12), []byte("data"), []byte("ad"))
	ct[0] ^= 0xff
	if _, err := a.Decrypt(repeat(0, 12), ct, []byte("ad")); !errors.Is(err, ErrBadAuthenticator) {
		t.Fatalf("tampered aead: got %v", err)
	}
}

// --- Error tree ------------------------------------------------------------

func TestErrorTree(t *testing.T) {
	var le *LengthError
	_, err := NewSecretBox(repeat(0, 10))
	if !errors.As(err, &le) {
		t.Fatalf("expected *LengthError, got %T", err)
	}
	if le.Got != 10 || le.Want != SecretBoxKeyBytes {
		t.Fatalf("LengthError fields: got=%d want=%d", le.Got, le.Want)
	}
	if !errors.Is(err, ErrLength) || !errors.Is(err, ErrCrypto) {
		t.Fatal("LengthError should unwrap to ErrLength and ErrCrypto")
	}
	if le.Error() == "" {
		t.Fatal("empty LengthError message")
	}

	var bad *BadAuthenticatorError
	sb, _ := NewSecretBox(repeat(1, 32))
	ct, _ := sb.Encrypt(repeat(2, 24), []byte("x"))
	ct[0] ^= 1
	_, err = sb.Decrypt(repeat(2, 24), ct)
	if !errors.As(err, &bad) {
		t.Fatalf("expected *BadAuthenticatorError, got %T", err)
	}
	if !errors.Is(err, ErrBadAuthenticator) || !errors.Is(err, ErrCrypto) {
		t.Fatal("BadAuthenticatorError should unwrap to ErrBadAuthenticator and ErrCrypto")
	}
	if bad.Error() == "" {
		t.Fatal("empty BadAuthenticatorError message")
	}
}
